-- Reference data. Safe to run again: existing rows are left as they are, so later edits survive.
INSERT INTO subjects (code, name_ar, name_en, sort_order) VALUES
  ('math', 'الرياضيات', 'Mathematics', 1),
  ('english', 'اللغة الإنجليزية', 'English', 2),
  ('arabic', 'اللغة العربية', 'Arabic', 3),
  ('islamic_education', 'التربية الإسلامية', 'Islamic Education', 4),
  ('national_life_education', 'التربية الوطنية والحياتية', 'National and Life Education', 5),
  ('science_life', 'العلوم والحياة', 'Science and Life', 6),
  ('national_social_upbringing', 'التنشئة الوطنية والاجتماعية', 'National and Social Upbringing', 7),
  ('social_studies', 'الدراسات الاجتماعية', 'Social Studies', 8),
  ('tajweed', 'التلاوة والتجويد', 'Quran Recitation and Tajweed', 9),
  ('technology', 'التكنولوجيا', 'Technology', 10),
  ('programming', 'البرمجة', 'Programming', 11),
  ('arts_crafts', 'الفنون والحرف', 'Arts and Crafts', 12),
  ('french', 'اللغة الفرنسية', 'French', 13),
  ('vocational_education', 'التعليم المهني', 'Vocational Education', 14),
  ('physics', 'الفيزياء', 'Physics', 15),
  ('chemistry', 'الكيمياء', 'Chemistry', 16),
  ('biology', 'العلوم الحياتية', 'Biology', 17),
  ('palestine_geography_history', 'جغرافية فلسطين وتاريخها', 'Geography and History of Palestine', 18),
  ('digital_skills', 'المهارات الرقمية', 'Digital Skills', 19),
  ('geography', 'الدراسات الجغرافية', 'Geographical Studies', 20),
  ('history', 'الدراسات التاريخية', 'Historical Studies', 21),
  ('scientific_culture', 'الثقافة العلمية', 'Scientific Culture', 22),
  ('quran_sciences', 'القرآن الكريم وعلومه', 'The Holy Quran and Its Sciences', 23),
  ('hadith_sciences', 'الحديث الشريف وعلومه', 'Hadith and Its Sciences', 24),
  ('fiqh', 'الفقه الإسلامي', 'Islamic Jurisprudence', 25),
  ('aqidah', 'العقيدة', 'Islamic Creed', 26),
  ('islamic_systems', 'النظم الإسلامية', 'Islamic Systems', 27),
  ('dawah_rhetoric', 'أساليب الدعوة وفن الخطابة', 'Dawah Methods and Public Speaking', 28),
  ('management_economics', 'الإدارة والاقتصاد', 'Management and Economics', 29),
  ('accounting', 'المحاسبة', 'Accounting', 30),
  ('small_projects', 'المشاريع الصغيرة', 'Small Projects', 31),
  ('entrepreneurship', 'الريادة في الأعمال', 'Entrepreneurship', 32),
  ('technical_drawing', 'الرسم الصناعي', 'Technical Drawing', 33),
  ('communications_electronics', 'الاتصالات والإلكترونيات', 'Communications and Electronics', 34),
  ('programming_automation', 'البرمجة والأتمتة', 'Programming and Automation', 35),
  ('graphic_design', 'التصميم الجرافيكي', 'Graphic Design', 36),
  ('industrial_electronics', 'الإلكترونيات الصناعية', 'Industrial Electronics', 37),
  ('automotive_electrics', 'كهرباء سيارات', 'Automotive Electrics', 38),
  ('electrical_installations', 'كهرباء استعمال', 'Electrical Installations', 39)
ON CONFLICT (code) DO NOTHING;
--> statement-breakpoint
INSERT INTO section_types (key, name_ar, name_en, icon, color, exts, links, sort_order) VALUES
  ('videos', 'الفيديوهات', 'Videos', 'video', 'coral', '["mp4", "mov"]'::jsonb, true, 1),
  ('files', 'الملفات', 'Files', 'file', 'blue', '["pdf", "doc", "docx", "ppt", "pptx", "xls", "xlsx"]'::jsonb, true, 2),
  ('images', 'الصور', 'Images', 'image', 'teal', '["png", "jpg", "jpeg", "webp"]'::jsonb, false, 3),
  ('presentations', 'العروض التقديمية', 'Presentations', 'presentation', 'ochre', '["ppt", "pptx", "pdf"]'::jsonb, true, 4),
  ('lesson_plans', 'خطط الدروس', 'Lesson Plans', 'clipboard', 'green', '["pdf", "doc", "docx"]'::jsonb, true, 5),
  ('worksheets', 'أوراق العمل', 'Worksheets', 'pencil', 'blue', '["pdf", "doc", "docx"]'::jsonb, true, 6),
  ('posters', 'الملصقات', 'Posters', 'image', 'plum', '["png", "jpg", "jpeg", "webp", "pdf"]'::jsonb, true, 7),
  ('links', 'الروابط', 'Links', 'link', 'blue', '[]'::jsonb, true, 8)
ON CONFLICT (key) DO NOTHING;
